package x1.model;

public enum TokenType {
  EOF, IDENTIFIER, NUMBER, PLUS, MINUS, PACKAGE, IMPORT, TYPE, FUNCTION, VAR, IF, ELSE, FOR, RETURN, TRUE, MULTIPLY, DIVIDE, LPAREN, RPAREN, EQUAL_EQUAL, EQUAL, STRING_LITERAL, BOOLEAN_LITERAL, DOT, COLON, COMMA, LBRACE, RBRACE, SEMICOLON, NOT, NOT_EQUAL, LESS_EQUAL, LESS, GREATER_EQUAL, GREATER, AND, OR, MODULO, LBRACKET, RBRACKET, FALSE
  // Add other token types here...
}